### ISSUE TITLE
internal/examples/supervisor: nil pointer dereference

### ISSUE THREAD

**Issue by gbbr** [open-telemetry/opamp-go#168]
Clone the repo, then follow these steps (as per [blog post](https://opentelemetry.io/blog/2022/opamp/)):

```
$ cd internal/examples/supervisor/bin
$ go run ../main.go 
2023/05/15 10:17:09 Supervisor starting, id=01H0F4AAXT06AFVGQT5ZYC0GEK, type=io.opentelemetry.collector, version=1.0.0.
2023/05/15 10:17:09 Starting OpAMP client...
2023/05/15 10:17:09 OpAMP Client started.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10100307c]

goroutine 36 [running]:
github.com/open-telemetry/opamp-go/internal/examples/supervisor/supervisor.(*Supervisor).runAgentProcess(0x1400019b520)
	/Users/gbbr/go/src/github.com/open-telemetry/opamp-go/internal/examples/supervisor/supervisor/supervisor.go:502 +0xdc
created by github.com/open-telemetry/opamp-go/internal/examples/supervisor/supervisor.NewSupervisor
	/Users/gbbr/go/src/github.com/open-telemetry/opamp-go/internal/examples/supervisor/supervisor/supervisor.go:110 +0x4bc
exit status 2
```

Contents of `supervisor.yaml`:

```yaml
server:
  endpoint: ws://127.0.0.1:4320/v1/opamp

agent:
  executable: ../../../../../opentelemetry-collector-contrib/bin/otelcontribcol_darwin_amd64
```

**Comment by gbbr** [comment]
It seems to be because of an expectation for the `effective.yaml` file to be there, which it isn't, and none of the instructions or log messages mention it.

**Comment by srikanthccv** [comment]
@gbbr I believe this PR https://github.com/open-telemetry/opamp-go/pull/166 fixed the issue. Please check and let us know.

**Comment by srikanthccv** [comment]
I verified this is no longer an issue.
